<Project Sdk="Microsoft.NET.Sdk.Web">
	<Target Name="CloseApp" BeforeTargets="Build;Compile;PreBuildEvent">
		<Message Importance="high" Text=" DEBUG: Closing existing process" />
		<PropertyGroup>
			<TearDownScriptPath>C:\Users\aim4r\Documents\Projects\Velo-Forum\UI\ui-forum-app\AppDown.ps1</TearDownScriptPath>
		</PropertyGroup>
		<Exec Command="powershell.exe -ExecutionPolicy Bypass -File &quot;$(TearDownScriptPath)&quot;"></Exec>
	</Target>
	<!--<Target Name="RunMyScriptAfterBuild" AfterTargets="PostBuildEvent">
		<PropertyGroup>
			<ExecScriptPath>C:\Users\aim4r\Documents\Projects\Velo-Forum\UI\ui-forum-app\AppExec.ps1</ExecScriptPath>
		</PropertyGroup>
		<Message Importance="high" Text=" DEBUG: Запускаю скрипт из папки: $(ProjectDir)"/>		
		<Exec Command="powershell.exe -ExecutionPolicy Bypass -File &quot;$(ExecScriptPath)&quot;"></Exec>
	</Target>-->
	<ItemGroup>
		<None Include="*.pem">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Forum.Application\Forum.Application.csproj" />
		<ProjectReference Include="..\Forum.Infrastructure\Forum.Infrastructure.csproj" />
	</ItemGroup>
</Project>
